### ISSUE TITLE
是否可能在 WSL 中调用 Windows 系统中的字体

### ISSUE THREAD

**Issue by kexplorning** [OsbertWang/install-latex-guide-zh-cn#14]
Windows 系统中有很多自带的字体，希望 WSL 也能调用。

虽然直接指定 `Path = /mnt/c/Windows/Fonts/` 这样暴力挑选字体也是可以的，但是不能按照字体名来选择。

是否有办法？

**Comment by OsbertWang** [comment]
这不是本手册要考虑的内容，应该归类为 WSL-usage

**Comment by kexplorning** [comment]
呃，这不算作完全不相关吧，毕竟 Ubuntu 安装的时候，也要把字体配置好，让系统识别（这样可以用字体名称调用）。

**Comment by OsbertWang** [comment]
我刚刚查了一下，或许有问过这样问题的。
[参考这里](https://x410.dev/cookbook/wsl/sharing-windows-fonts-with-wsl/)

**Comment by kexplorning** [comment]
好吧，如此简单。。和 Ubuntu 中添加字体识别一模一样。。

建议可以加个注释什么的。

**Comment by OsbertWang** [comment]
回头加在手册里好了

**Comment by kexplorning** [comment]
等等，之前没看到 附录A。。这样的话，可以直接在 Windows 上安装字体，然后在 WSL 刷新一下，然后就可以用了。

**Comment by OsbertWang** [comment]
嗯，可以的

**Comment by kexplorning** [comment]
并且节省了很多空间，比如安装全套思源黑体 + 思源宋体。。

**Comment by OsbertWang** [comment]
WSL 里还有很多坑，是我这个手册无法都指出的，毕竟它主要的任务是 install，不是 use

**Comment by OsbertWang** [comment]
此处内容已在 install-latex 中添加脚注。
待更新后，我将关闭此 issue

**Comment by OsbertWang** [comment]
鉴于 WSL2 和主系统文件系统互访速度慢，该方法很可能拖慢 `xelatex` 速度，特此声明。
