### ISSUE TITLE
windows 下卸载 tl 时的注册表清理位置

### ISSUE THREAD

**Issue by tanukihee** [OsbertWang/install-latex-guide-zh-cn#21]
目前版本中关于 win 下手动卸载 tl 的介绍中，需要手动清理 HKCU 下的三条注册表。

https://github.com/OsbertWang/install-latex-guide-zh-cn/blob/d7eaa373844e534133b85d223c3b55dad9311bdc/chapter/windows.tex#L282-L287

但若在安装时使用管理员权限「为所有人安装」后，此三条注册表并不在 HKCU 下，而在 HKLM 下。

**Comment by OsbertWang** [comment]
已改。
