### ISSUE TITLE
文档中的WSL版本是什么？

### ISSUE THREAD

**Issue by Winson-Huang** [OsbertWang/install-latex-guide-zh-cn#28]
目前[WSL1和WSL2](https://docs.microsoft.com/en-us/windows/wsl/compare-versions)同时存在，但两者有较多不同，不知此文档中的安装步骤适用WSL1还是WSL2？亦或两者均可？谢谢

**Comment by OsbertWang** [comment]
我自己好像在 WSL1 和 WSL2 都安装过来着。
你安装出现了什么问题的话，可以直接提出来，大家共同探讨。

**Comment by Winson-Huang** [comment]
WSL2中安装后测试没有发现什么问题。
