### ISSUE TITLE
Win 下，TeX Live 2023 的二进制文件路径变为 `<TEXDIR>/bin/windows`

### ISSUE THREAD

**Issue by muzimuzhi** [OsbertWang/install-latex-guide-zh-cn#35]
texlive 2023 起，windows 下提供 64 位的二进制文件。对应的，路径 `<TEXDIR>/bin/win32` 变为 `<TEXDIR>/bin/windows`。

见 The TeX Live Guide—2023, [sec. 9.2 Present: 2023](https://tug.org/texlive/doc/texlive-en/texlive-en.html#x1-920009.2)
> Windows: As announced previously, TeX Live now contains 64-bit Windows binaries instead of 32-bit. The new directory name is bin/windows (it did not seem right to put 64-bit binaries into a directory named with “32”).

涉及的修改。需要额外提及「TeX Live 2023 之前为 `bin/win32`」吗？
```diff
diff --git a/chapter/editor.tex b/chapter/editor.tex
index e7941ff..8a7f99a 100644
--- a/chapter/editor.tex
+++ b/chapter/editor.tex
@@ -20,7 +20,7 @@
 和大多数国产软件不同, \TeX works 不会自动在桌面生成快捷方式,
 新人往往不知道如何打开它. 
 实际上 \TeX works 在 \TeX{} Live 安装路径的
-\texttt{\textbackslash bin\textbackslash win32} 中,
+\texttt{\textbackslash bin\textbackslash windows} 中,
 可在 \textsf{cmd} 中执行 \texttt{texworks} 打开,
 也可直接在 Windows 搜索栏里搜 \TeX works 打开. 
 
diff --git a/chapter/windows.tex b/chapter/windows.tex
index 3e24d45..30c1d75 100644
--- a/chapter/windows.tex
+++ b/chapter/windows.tex
@@ -204,7 +204,7 @@
 \end{lstlisting}
 即可认为安装顺利完成%
 \footnote{若未能正确显示结果, 则可能是因为环境变量未改变,
-用户可手动添加 \texttt{<TEXDIR>\textbackslash bin\textbackslash win32} 至环境变量,
+用户可手动添加 \texttt{<TEXDIR>\textbackslash bin\textbackslash windows} 至环境变量,
 \texttt{<TEXDIR>} 需与你方才的安装路径一致}.
 弹出前面装载的光盘镜像,
 安装到此结束.
```

未win 跨版本升级尚不支持，无需提及这个路径变化。

------
`CTeX-org/ctex-kit` 最近一次的定时测试失败了，在尝试修复时发现了这个变化，
- 失败的 workflow run https://github.com/muzimuzhi/ctex-kit/actions/runs/4514955570/jobs/7951671140
- 更新 path 后，通过的 workflow run https://github.com/muzimuzhi/ctex-kit/actions/runs/4520086911/jobs/7960972483

**Comment by muzimuzhi** [comment]
> 需要额外提及「TeX Live 2023 之前为 `bin/win32`」吗？

换个说法：`install-latex-guide-zh-cn` 是不是只介绍如何安装发行版的最新版本？

看起来是的。我没有通读过这个 guide 的全文，但假设「介绍如何安装历史版本，肯定会提及 https://ftp.math.utah.edu/pub/tex/historic」，我搜了 "historic" 没搜到。

**Comment by OsbertWang** [comment]
这两处错误已经更改

**Comment by OsbertWang** [comment]
> > 需要额外提及「TeX Live 2023 之前为 `bin/win32`」吗？
> 
> 换个说法：`install-latex-guide-zh-cn` 是不是只介绍如何安装发行版的最新版本？
> 
> 看起来是的。我没有通读过这个 guide 的全文，但假设「介绍如何安装历史版本，肯定会提及 https://ftp.math.utah.edu/pub/tex/historic 」，我在 repo 里全文搜 "historic" 没搜到。

嗯，我目前是打算只介绍最新的，历史包袱我背不动。
