### ISSUE TITLE
如果 Tex Live 大版本发布但本地未更新，tlmgr 无法正常安装/更新 package

### ISSUE THREAD

**Issue by Winson-Huang** [OsbertWang/install-latex-guide-zh-cn#36]
手册中使用 `tlmgr option repository ctan` 自动获取仓库 URL 或者手动配置的仓库镜像都会随 texlive 发行版更新，如果用户不希望每年都重新安装一次 texlive 发行版，那么每次 texlive 发布新版本后这个仓库 URL 就无法使用了。

对于这类用户，可以参考[此帖](https://tex.stackexchange.com/a/580117)和[相关 tug 页面](https://tug.org/historic/)，合适地配置 tlmgr。

如果作者愿意加入这部分内容的话我可以提 pr。

**Comment by OsbertWang** [comment]
我考虑了一下这个情况，决定还是暂不加入。理由如下：

- 时至今日，在 [Update](https://www.tug.org/texlive/upgrade.html) 页面都保留这样的话，这表明自旧版本升级为新版本并非 TUG 赞成的方式。

> By default, please get the new TL by [doing a new installation](https://www.tug.org/texlive/quickinstall.html) instead of proceeding here.
> There is no comparable upgrade procedure for Windows. Doing a new installation is necessary.

- 今年（2023年），TeX Live 启用 64 位程序，直接从 TeX Live 2022 升级为 2023 不可避免地还会牵扯到系统文件夹（名）的更换，这对于安装而言并不是简易的事情。从时间成本来考虑，排查各类兼容问题的时间未必会比直接卸载重装短，尤其是使用本手册的大部分人是对系统不了解的入门级用户。

基于以上，我暂不加入这些内容。

**Comment by muzimuzhi** [comment]
感觉这里有两件不同的事
- 想在 texlive 的新年度版本发布后，继续使用旧版本并有限地安装并更新包（只能安装到旧 texlive 最后包含的包的版本），可以设置 historic ctan mirror
- 想跨 texlive 版本升级

@Winson-Huang 你说的是第一个，有限的包安装和更新吗？

**Comment by OsbertWang** [comment]
> 感觉这里有两件不同的事
> 
> * 想在 texlive 的新年度版本发布后，继续使用旧版本并有限地安装并更新包（只能安装到旧 texlive 最后包含的包的版本），可以设置 historic ctan mirror
> * 想跨 texlive 版本升级
> 
> @Winson-Huang 你说的是第一个，有限的包安装和更新吗？

有道理，我理解错了。第一种情况，我不太建议这么做。

**Comment by Winson-Huang** [comment]
@muzimuzhi 是的，我说的就是第一件事
