### ISSUE TITLE
macOS安装教程中，与Homebrew有关的内容已过时

### ISSUE THREAD

**Issue by tauyoungsama** [OsbertWang/install-latex-guide-zh-cn#38]
第3章安装MacTeX一节中，与Homebrew有关的内容已过时，需要重新编写。

- Homebrew的安装命令不需要`ruby`，且目前[官网](https://brew.sh/)给出的安装命令与文档中的不同。
```sh
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```
- 更改镜像的命令是建立在用户已经从官方源成功安装Homebrew的基础上，如果用户无法安装，同样也无法修改镜像源；应增加直接从镜像源安装的教程。
- Homebrew安装时会自动安装Xcode CLI，用户无需手动安装；并且Homebrew需要的仅仅是Xcode CLI（命令行工具），不需要安装整个XCode。
- `brew cask`命令已被废弃，新的安装命令为`brew install --cask mactex`，升级命令为`brew upgrade mactex`。
- Homebrew还提供了不安装GUI组件的选项，命令为`brew install --cask mactex-no-gui`，适合仅从命令行编译或使用其他文本编辑器的用户。

**Comment by OsbertWang** [comment]
您好啊，由于我本人并不使用 macOS，这部分内容原来由另一位朋友起草，我稍做文字修订。如果可以，能否请您起草一份，提交一个 pull requests 上来？
